services:
  app:
    build: .
    command: ["bash", "-c", "while true; do python main.py; sleep 600; done"]
    volumes:
      - ./data/raw_mis:/app/data/raw_mis
      - ./data/processed_csv:/app/data/processed_csv
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - FTP_SERVER
      - FTP_PORT
      - FTP_USER
      - FTP_PASS
      - FTP_DIR
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE
      - MB_DB_DBNAME
      - MB_DB_PORT
      - MB_DB_USER
      - MB_DB_PASS
      - MB_DB_HOST
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata: