services:
  app:
    build: .
    command: ["bash", "-c", "while true; do python main.py; sleep 600; done"]
    volumes:
      - ./data/raw_mis:/app/data/raw_mis
      - ./data/processed_csv:/app/data/processed_csv
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=weather_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lion2266
      - FTP_SERVER=178.216.209.185
      - FTP_PORT=47855
      - FTP_USER=Hydras
      - FTP_PASS=Ott_user
      - FTP_DIR=/path_1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=weather_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lion2266
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=weather_data
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=lion2266
      - MB_DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata: